name: Rollback

on:
  workflow_dispatch: # 手動トリガー
    inputs:
      target_tag:
        description: 'ターゲットとなるタグ名'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get commit hash of target tag
  run: |
    if [ -z "$IS_PROD_ENV" ]; then
      COMMIT_TARGET=$(git show --pretty=format:%H --no-patch stg-v2.0)
      echo "Commit hash of stg-v2.0 tag: $COMMIT_TARGET"
    else
      COMMIT_TARGET=$(git show --pretty=format:%H --no-patch origin/stg-v2.0)
      echo "Commit hash of stg-v2.0 tag: $COMMIT_TARGET"
    fi
  shell: /usr/bin/bash -ex

      
      - name: Get commit hash of environment branch
        run: |
          if [ -z "$IS_PROD_ENV" ]; then
            COMMIT_ENV=$(git show --pretty=format:%H --no-patch $ENV_BRANCH)
            echo "Commit hash of $ENV_BRANCH branch: $COMMIT_ENV"
          else
            COMMIT_ENV=$(git show --pretty=format:%H --no-patch origin/$ENV_BRANCH)
            echo "Commit hash of $ENV_BRANCH branch: $COMMIT_ENV"
          fi
      
      - name: Verify if commit hashes match
        run: |
          if [ "$COMMIT_TARGET" != "$COMMIT_ENV_STG" ]; then
            echo "Commit hashes of ${{ github.event.inputs.target_tag }} tag and env/stg branch do not match. Rollback aborted."
            exit 1
          else
            echo "Commit hashes of ${{ github.event.inputs.target_tag }} tag and env/stg branch match."
          fi

      - name: Get previous release tag
        run: |
          if [ -z "$IS_PROD_ENV" ]; then
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^)
            echo "Previous tag: $PREVIOUS_TAG"
          else
            PREVIOUS_TAG=$(git describe --tags --abbrev=0 origin/HEAD^)
            echo "Previous tag: $PREVIOUS_TAG"
          fi
      
      - name: Check if previous release tag exists
        run: |
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "Previous release tag does not exist. Rollback aborted."
            exit 1
          else
            echo "Previous release tag exists: $PREVIOUS_TAG"
          fi
      
      - name: Rollback to previous release
        run: |
          if [ -z "$IS_PROD_ENV" ]; then
            git checkout env/prod
            git reset --hard $PREVIOUS_TAG
            git push --force origin env/prod
          fi
